
def alfabeto(x):
    for c in x:
        match c:
            case 'a':
                print(' ______      ')
                print('/\  _  \     ')
                print('\ \ \L\ \    ')
                print(' \ \  __ \   ')
                print('  \ \ \/\ \  ')
                print('   \ \_\ \_\ ')
                print('    \/_/\/_/ ')
            case 'b':
                print(' ____       ')
                print('/\  _`\     ')
                print('\ \ \L\ \   ')
                print(' \ \  _ <   ')
                print('  \ \ \L\ \ ')
                print('   \ \____/ ')
                print('    \/___/  ')
            case 'c':
                print(' ____       ')
                print('/\  _`\     ')
                print('\ \ \/\_\   ')
                print(' \ \ \/_/_  ')
                print('  \ \ \L\ \ ')
                print('   \ \____/ ')
                print('    \/___/  ')
            case 'd':
                print(' ____       ')
                print('/\  _`\     ')
                print('\ \ \/\ \   ')
                print(' \ \ \ \ \  ')
                print('  \ \ \_\ \ ')
                print('   \ \____/ ')
                print('    \/___/  ')
            case 'e':
                print(' _______       ')
                print('|\  ___ \      ')
                print('\ \   __/|     ')
                print(' \ \  \_|/__   ')
                print('  \ \  \_|\ \  ')
                print('   \ \_______\ ')
                print('    \|_______| ')
            case 'f':
                print(' ________  ')
                print('|\  _____\ ')
                print('\ \  \__/  ')
                print(' \ \   __\ ')
                print('  \ \  \_| ')
                print('   \ \__\  ')
                print('    \|__|  ')
            case 'g':
                print('      ___      ')
                print('     /\  \     ')
                print('    /  \  \    ')
                print('   / /\ \  \   ')
                print('  / /  \ \  \  ')
                print(' / /__/_\ \__\ ')
                print(' \ \  /\ \/__/ ')
                print('  \ \ \ \__\   ')
                print('   \ \/ /  /   ')
                print('    \/___/     ')
            case 'h':
                print(' ___  ___      ')
                print('|\  \|\  \     ')
                print('\ \  \\\  \    ')
                print(' \ \   __  \   ')
                print('  \ \  \ \  \  ') 
                print('   \ \__\ \__\ ')
                print('    \|__|\|__| ')
            case 'i':
                print(' ___      ')
                print('|\  \     ')
                print('\ \  \    ')
                print(' \ \  \   ')
                print('  \ \  \  ')
                print('   \ \__\ ')
                print('    \|__| ')
            case 'j':
                print('    ___      ')
                print('   |\  \     ')
                print('   \ \  \    ')
                print(' __ \ \  \   ')
                print('|\  \\_\  \  ')
                print('\ \________\ ')
                print(' \|________| ')
            case 'k':
                print(' ___  __        ')
                print('|\  \|\  \      ')
                print('\ \  \/  /|_    ')
                print('  \ \  \\ \  \  ')
                print('   \ \__\\ \__\ ')
                print('    \|__| \|__| ')
            case 'l':
                print(' ___           ')
                print('|\  \          ')
                print('\ \  \         ')
                print(' \ \  \        ')
                print('  \ \  \____   ')
                print('   \ \_______\ ')
                print('    \|_______| ')
            case 'm':
                print(' _____ ______       ')
                print('|\   _ \  _   \     ')
                print('\ \  \\\__\ \  \    ')
                print(' \ \  \\|__| \  \   ')
                print('  \ \  \    \ \  \  ')
                print('   \ \__\    \ \__\ ')
                print('    \|__|     \|__| ')
            case 'n':
                print(' ________       ')
                print('|\   ___  \     ')
                print('\ \  \\ \  \    ')
                print(' \ \  \\ \  \   ')
                print('  \ \  \\ \  \  ')
                print('   \ \__\\ \__\ ')
                print('    \|__| \|__| ')
            case 'o':
                print(' ________       ')
                print('|\   ___  \     ')
                print('\ \  \ \\  \    ')
                print(' \ \  \ \\  \   ')
                print('  \ \  \_\\  \  ')
                print('   \ \________\ ')
                print('    \|________| ')
            case 'p':
                print(' ________    ')
                print('|\   __  \   ')
                print('\ \  \|\  \  ')
                print(' \ \   ____\ ')
                print('  \ \  \___| ')
                print('   \ \__\    ')
                print('    \|__|    ')
            case 'q':
                print(' ________       ')
                print('|\   __  \      ')
                print('\ \  \|\  \     ')
                print(' \ \_____  \   ')
                print('  \|____|\__\ ')
                print('        \|__| ')
            case 'r':
                print(' ________      ')
                print('|\   __  \     ')
                print('\ \  \|\  \    ')
                print(' \ \   _  _\   ')
                print('  \ \  \\  \|  ')
                print('   \ \__\\ _\  ')
                print('    \|__|\|__| ')
            case 's':
                print(' ________       ')
                print('|\   ____\      ')
                print('\ \  \___|_     ')
                print('  \|____|\  \   ')
                print('    ____\_\  \  ')
                print('   |\_________\ ')
                print('   \|_________| ')
            case 'p':
                print(' _________    ')
                print('|\___   ___\  ')
                print('\|___ \  \_|  ')
                print('      \ \  \  ')
                print('       \ \__\ ')
                print('        \|__| ')

            